SELECT 
	S.ID AS SESSIONID,
	U.ID AS USERID,
	U.USER_NAME AS USERNAME,
	U.LAST_NAME AS LASTNAME,
	U.FIRST_NAME AS FIRSTNAME,
	S.CREATED_DATE AS LOGGEDINSINCE 
FROM 
	CMN_SESSIONS S,
	CMN_SEC_USERS U
WHERE 
	U.ID=S.USER_ID
AND 
	S.ID = (SELECT MAX(ID) FROM CMN_SESSIONS WHERE USER_ID = S.USER_ID)
