SELECT
	BPN_R.ID AS ID,
	BPN_V.NAME AS NAME,
	BPN_O.OBJECT_ID AS OBJECT_ID,
	BPN_O.OBJECT_TYPE_CODE AS OBJECT_TYPE_CODE,
	BPN_R.STATUS_CODE AS STATUS_CODE,
	BPN_R.START_DATE AS START_DATE,
	BPN_R.END_DATE AS END_DATE,
	CASE 
		WHEN BPN_R.END_DATE IS NULL THEN ROUND(SYSDATE - BPN_R.START_DATE)
		END QTD_DIAS_INI,
	CASE 
		WHEN ROUND(SYSDATE - BPN_R.START_DATE) <= 30 THEN 0
		WHEN ROUND(SYSDATE - BPN_R.START_DATE) > 30 AND ROUND(SYSDATE - BPN_R.START_DATE) <= 50 THEN 1
		WHEN ROUND(SYSDATE - BPN_R.START_DATE) > 50 THEN 2
		END INDICADOR_TEMPO,
	TO_CHAR(BPN_R.START_DATE,'DD/MM/YYYY HH24\:MI\:SS') AS START_DATE,
	TO_CHAR(BPN_R.END_DATE,'DD/MM/YYYY HH24\:MI\:SS') AS END_DATE,
	TO_CHAR(TO_DATE('00\:00\:00','HH24\:MI\:SS') + (BPN_R.END_DATE - BPN_R.START_DATE), 'MI\:SS') AS DIFF,
	FLOOR((BPN_R.END_DATE - BPN_R.START_DATE) * 24 * 60 * 60) AS DIFF_SEC
FROM
	BPM_RUN_PROCESSES BPN_R
LEFT JOIN 
	BPM_DEF_PROCESSES_V BPN_V 
	ON BPN_R.PROCESS_VERSION_ID = BPN_V.ID 
	AND BPN_V.LANGUAGE_CODE = 'en'
LEFT JOIN 
	BPM_RUN_OBJECTS BPN_O 
	ON BPN_R.ID = BPN_O.PK_ID 
	AND BPN_O.TYPE_CODE = 'BPM_POT_PRIMARY'
ORDER BY BPN_R.START_DATE 

 
