SELECT 
    CCNP.NAME PROCESS_NAME,
    BDP.PROCESS_CODE,
    CCNS.NAME STEP,
    CCNA.NAME ACTION,
    CCS.SCRIPT_TEXT,
    BDPV.USER_STATUS_CODE PROCESS_STATUS,
    BDP.CREATED_DATE
FROM 
    BPM_DEF_PROCESSES bdp,
    CMN_CAPTIONS_NLS ccnp,
    BPM_DEF_PROCESS_VERSIONS bdpv,
    BPM_DEF_STAGES bdstg,
    BPM_DEF_STEPS bds,
    CMN_CAPTIONS_NLS ccns,
    BPM_DEF_STEP_ACTIONS bdsa,
    CMN_CAPTIONS_NLS ccna,
    CMN_CUSTOM_SCRIPTS ccs
WHERE 
CCNP.TABLE_NAME       ='BPM_DEF_PROCESSES'
AND CCNP.LANGUAGE_CODE      ='en'
AND CCNP.PK_ID              =BDP.ID
AND BDPV.PROCESS_ID         =BDP.ID
AND BDSTG.PROCESS_VERSION_ID=BDPV.ID
AND BDS.STAGE_ID            =BDSTG.ID
AND CCNS.TABLE_NAME         ='BPM_DEF_STEPS'
AND CCNS.LANGUAGE_CODE      ='en'
AND CCNS.PK_ID              =BDS.ID
AND BDSA.STEP_ID            =BDS.ID
AND CCNA.TABLE_NAME         ='BPM_DEF_STEP_ACTIONS'
AND CCNA.LANGUAGE_CODE      ='en'
AND CCNA.PK_ID              =BDSA.ID
AND CCS.ID                  =BDSA.SCRIPT_ID
AND CCS.LANGUAGE_CODE       = 'gel'
AND UPPER(CCS.SCRIPT_TEXT) LIKE UPPER('%gel:log%') -- check tag
AND BDPV.USER_STATUS_CODE = 'BPM_PUS_ACTIVE'
ORDER BY CCNP.NAME, CCNS.NAME, CCNA.NAME, BDP.CREATED_DATE
