SELECT 
    AI.CREATED_DATE,
    AI.SUBJECT ACTION_ITEM,
    AI.DESCRIPTION DESC_ITEM_ACAO,
    NAMESTEP.NAME STEP,
    PROCDEF.PROCESS_CODE PROCESS_CODE,
    NAMEPROC.NAME PROCESS_NAME,
    STEPDEF.STEP_CODE STEP_CODE,
    USR.FIRST_NAME,
    USR.LAST_NAME
FROM 
    BPM_RUN_PROCESSES RUNPROC
JOIN 
    BPM_RUN_STEPS RUNSTEP
JOIN 
    BPM_DEF_STEPS STEPDEF
LEFT JOIN 
    CMN_CAPTIONS_NLS NAMESTEP
    ON STEPDEF.ID = NAMESTEP.PK_ID AND NAMESTEP.LANGUAGE_CODE = 'pt' AND NAMESTEP.TABLE_NAME = 'BPM_DEF_STEPS'
    ON RUNSTEP.STEP_ID = STEPDEF.ID 
JOIN 
    BPM_RUN_STEP_ACTION_RESULTS RUNSTEPACT 
JOIN 
    CAL_ACTION_ITEMS AI
JOIN 
    CAL_ACTION_ITEM_ASSIGNEES AIASS
JOIN 
    CMN_SEC_USERS USR 
    ON AIASS.ASSIGNEE_ID = USR.ID 
    ON AI.ID = AIASS.CAL_ACTION_ITEM_ID AND AIASS.STATUS_CODE = 'CAL_OPEN' -- status
    ON RUNSTEPACT.ID = AI.PROCESS_HANDLER_ID
    ON RUNSTEP.ID = RUNSTEPACT.STEP_INSTANCE_ID
    ON RUNPROC.ID = RUNSTEP.PROCESS_INSTANCE_ID
JOIN 
    BPM_DEF_PROCESS_VERSIONS DEFPROCVER
JOIN 
    BPM_DEF_PROCESSES PROCDEF
    ON PROCDEF.ID = DEFPROCVER.PROCESS_ID 
LEFT JOIN 
    CMN_CAPTIONS_NLS NAMEPROC
    ON DEFPROCVER.PROCESS_ID = NAMEPROC.PK_ID AND NAMEPROC.LANGUAGE_CODE = 'pt' AND NAMEPROC.TABLE_NAME = 'BPM_DEF_PROCESSES'
    ON RUNPROC.PROCESS_VERSION_ID = DEFPROCVER.ID 
JOIN 
    BPM_RUN_OBJECTS RUNOBJ 
    ON RUNPROC.ID = RUNOBJ.PK_ID 
    AND RUNOBJ.TABLE_NAME = 'BPM_RUN_PROCESSES'
    AND RUNOBJ.TYPE_CODE = 'BPM_POT_PRIMARY'
