SELECT 
	USER_ID, 
	ID ACTION_ITEM_ID, 
	OBJECT_TYPE_NAME, 
	OBJECT_ID,
	SUB_OBJECT_TYPE, 
	SUB_OBJECT_ID, 
	PROCESS_HANDLER_ID
FROM 
	CAL_ALL_ACTION_ITEMS_V
WHERE 
	LANGUAGE_CODE = 'en'
AND 
	USER_ID != 8
-- AND USER_ID = 1
AND (STATUS_CODE IS NULL )
AND NOT EXISTS
			(SELECT 
				RP.ID PROCESS_INSTANCE_ID, 
				RP.PROCESS_VERSION_ID, 
				RS.STEP_ID
			FROM 
				BPM_RUN_STEP_ACTION_RESULTS SAR, 
				BPM_RUN_STEPS RS, 
				BPM_RUN_PROCESSES RP
			WHERE 
				SAR.ID = PROCESS_HANDLER_ID
			AND 
				SAR.STEP_INSTANCE_ID = RS.ID
			AND 
				RP.ID = RS.PROCESS_INSTANCE_ID
			)
AND PROCESS_HANDLER_ID IS NOT NULL
