SELECT
	AI.ID IA_ID,
	AIASS.ASSIGNEE_ID USER_ID,
	RUNPROC.ID PROC_ID,
	AIASS.STATUS_CODE
FROM
	CAL_ACTION_ITEMS AI
JOIN 
	BPM_RUN_STEP_ACTION_RESULTS PROCRESULTS
		ON PROCRESULTS.AI_ID = AI.ID
JOIN 
	CAL_ACTION_ITEM_ASSIGNEES AIASS
		ON AI.ID = AIASS.CAL_ACTION_ITEM_ID
LEFT JOIN 
	CMN_SEC_USERS USRORIGINAL 
		ON AIASS.IS_PROXY = 1 
		AND AIASS.PROXY_SOURCE_ID = USRORIGINAL.ID        
JOIN 
	BPM_RUN_STEPS RUNSTEP
        ON PROCRESULTS.STEP_INSTANCE_ID = RUNSTEP.ID
JOIN 
	BPM_RUN_PROCESSES RUNPROC
        ON RUNPROC.ID = RUNSTEP.PROCESS_INSTANCE_ID
WHERE    
  AIASS.ASSIGNEE_ID = ?
